### ISSUE TITLE
Wheels for newer versions of PyICU

### ISSUE THREAD

**Issue by takiarek** [jessamynsmith/pyicu-wheels#2]
Hi!

Thank you very much for this repository of PyICU wheels, it's very helpful!

I need wheels for newer versions of PyICU (1.9.8 & 2.0.3) and I couldn't generate them on Heroku. I always get `unable to execute 'gcc': No such file or directory`. Apt buildback doesn't help me with this. I'm not sure if I'm setting the flags and other stuff correctly. Have you had similar problems with this?

I wonder if you could describe what steps did you take to create PyICU wheels. I will happily create a Pull Request with new wheels after I manage to generate them.

Thank you once again!

**Comment by jessamynsmith** [comment]
That's a great idea. Let me see if I can dig up exactly how I did it.

**Comment by takiarek** [comment]
Thanks @jessamynsmith, that would be very helpful!

**Comment by takiarek** [comment]
Hi,
I managed to generate those wheels by running Ubuntu on a virtual machine. He're  a PR with the generated linux wheels: https://github.com/jessamynsmith/pyicu-wheels/pull/3

**Comment by jessamynsmith** [comment]
Thank you. I did some research today and determined that it is no longer possible to easily generate the wheels on the new heroku stack, so your solution is the best. Thanks for the pull requests, I'll merge those now!

**Comment by jessamynsmith** [comment]
Thanks to your help, I've updated the readme with instructions for the current heroku stack. Thanks again!
